name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERUSERNAME }}
        password: ${{ secrets.DOCKERPASSWD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERUSERNAME }}/takkadapelly:${{ github.sha }} .
        docker push ${{ secrets.DOCKERUSERNAME }}/takkadapelly:${{ github.sha }}
